// Copy dos 30 carrosséis ZocLabs. O gerador (gen_art.mjs) cria 1 index.html por slug.
// slide.kind: cover | mid | practice | cta.  Destaque âmbar: <b class="a">palavra</b> (1 por slide).
// title = título EXATO do content_items (pra linkar a arte ao conteúdo no ZocLife).
export default [
// ===== Codex =====
{ slug:"c01-codex-explicado", pilar:"Codex", title:"Codex explicado pra quem trabalha com automacao", slides:[
  {kind:"cover", k:"Codex", h:`Você automatiza no Power Automate. O Codex faz isso no <b class="a">código</b>.`, b:`E ninguém te explicou direito o que ele é.`},
  {kind:"mid", k:"o que é", h:`Um agente que escreve e <b class="a">roda</b> código no terminal.`, b:`Você descreve em português; ele cria, executa, testa e corrige.`},
  {kind:"mid", k:"onde encaixa", h:`Você já faz isso — só que à mão.`, b:`Macro, fórmula, script de planilha. O Codex é a versão turbinada disso.`},
  {kind:"mid", k:"3 usos", h:`Pra quem é de automação:`, b:`Organizar arquivos · converter planilhas · gerar scripts repetitivos.`},
  {kind:"practice", k:"mão na massa", p:`1ª tarefa que eu daria: “organize esta pasta por data”. Vê ele fazer em <b class="a">1</b> comando.`},
  {kind:"cta", k:"seu próximo passo", h:`Salva pra testar o Codex.`, b:`Envia pro colega que vive preso no Excel.`},
]},
{ slug:"c02-testaria-primeiro-codex", pilar:"Codex", title:"O que eu testaria PRIMEIRO no Codex", slides:[
  {kind:"cover", k:"Codex", h:`Instalou o Codex e travou no <b class="a">“e agora?”</b>`, b:`Faz isso primeiro — sem medo de quebrar nada.`},
  {kind:"mid", k:"regra de ouro", h:`Comece numa pasta de <b class="a">teste</b>.`, b:`Nada de produção. Erro em ambiente seguro é aprendizado.`},
  {kind:"mid", k:"comando 1", h:`Peça pra ele explicar a pasta.`, b:`“O que tem aqui e o que cada arquivo faz?” Você entende o terreno.`},
  {kind:"mid", k:"comando 2 e 3", h:`Peça um script pequeno e mande testar.`, b:`Um problema real e simples. Depois: “rode e me mostre o resultado”.`},
  {kind:"practice", k:"mão na massa", p:`Meu 1º prompt real: “renomeie estes PDFs para AAAA-MM-DD-nome”. Resolveu em <b class="a">segundos</b>.`},
  {kind:"cta", k:"seu próximo passo", h:`Salva esse roteiro de início.`, b:`Comenta: o que você testaria primeiro?`},
]},
{ slug:"c03-codex-x-claudecode", pilar:"Codex", title:"Codex x Claude Code: qual usar em 2026?", slides:[
  {kind:"cover", k:"Comparativo", h:`Codex ou Claude Code? A resposta é mais <b class="a">simples</b> do que dizem.`, b:`O que cada um faz melhor — sem torcida.`},
  {kind:"mid", k:"Codex", h:`Forte no terminal e em tarefas longas.`, b:`Executa muitos passos sozinho e já opera apps do Windows.`},
  {kind:"mid", k:"Claude Code", h:`Forte em contexto e arquitetura.`, b:`Entende projeto inteiro, usa arquivos e despacha subagents.`},
  {kind:"mid", k:"a real", h:`Não é “o melhor”. É o <b class="a">certo</b> pra cada tarefa.`, b:`Muita gente usa os dois — um pra cada momento.`},
  {kind:"practice", k:"mão na massa", p:`Eu abro o Codex pra rodar tarefa no terminal; o Claude Code pra entender e mexer num projeto.`},
  {kind:"cta", k:"sua vez", h:`Comenta qual você usa hoje.`, b:`Salva a comparação pra decidir depois.`},
]},
{ slug:"c04-tarefas-chatas-codex", pilar:"Codex", title:"5 tarefas chatas que o Codex resolve no terminal", slides:[
  {kind:"cover", k:"Codex", h:`<b class="a">5</b> tarefas que você faz na mão e o Codex faz em 1 comando.`, b:`Salva essa lista.`},
  {kind:"mid", k:"1 e 2", h:`Renomear/organizar arquivos em massa. Converter planilha em JSON/CSV.`, b:`O tipo de coisa que come 40 minutos do seu dia.`},
  {kind:"mid", k:"3 e 4", h:`Gerar um script de backup. Limpar dados repetidos.`, b:`Ele escreve, roda e te mostra o antes/depois.`},
  {kind:"mid", k:"5", h:`Montar um relatório simples a partir de uma planilha.`, b:`“Some por mês e gere uma tabela” — pronto.`},
  {kind:"practice", k:"mão na massa", p:`Comando real: “junte todos os CSVs desta pasta num só”. <b class="a">1</b> linha, segundos.`},
  {kind:"cta", k:"sua vez", h:`Qual você testaria primeiro?`, b:`Salva e comenta.`},
]},
{ slug:"c05-codex-windows", pilar:"Codex", title:"Codex no Windows: agora ele clica sozinho", slides:[
  {kind:"cover", k:"Codex", h:`O Codex agora abre programas do Windows e clica <b class="a">sozinho</b>.`, b:`Sério. Isso mudou em 2026.`},
  {kind:"mid", k:"o que é", h:`Computer Use: ele vê a tela, clica e digita.`, b:`Deixa de “só escrever texto” e passa a operar a máquina.`},
  {kind:"mid", k:"o que dá pra fazer", h:`Tarefas repetitivas entre apps.`, b:`Copiar daqui, colar ali, preencher um formulário, exportar.`},
  {kind:"mid", k:"cuidado", h:`Sempre <b class="a">revise</b> antes de soltar.`, b:`Agente que clica sozinho precisa de supervisão no começo.`},
  {kind:"practice", k:"mão na massa", p:`Tarefa que eu deixaria: “abra o relatório, exporte em PDF e salve na pasta X”.`},
  {kind:"cta", k:"sua vez", h:`Salva isso.`, b:`Envia pra quem ainda acha que IA só escreve texto.`},
]},
{ slug:"c06-primeiro-script-codex", pilar:"Codex", title:"Do zero ao 1º script com Codex em 20 min", slides:[
  {kind:"cover", k:"Codex", h:`Nunca programou? Seu 1º script útil sai em <b class="a">20</b> minutos.`, b:`Com o Codex te guiando.`},
  {kind:"mid", k:"passo 1", h:`Instale e abra o Codex.`, b:`Não precisa entender a linguagem — você fala, ele escreve.`},
  {kind:"mid", k:"passo 2", h:`Descreva o problema em português.`, b:`“Quero juntar estas planilhas numa só, sem repetir nomes.”`},
  {kind:"mid", k:"passo 3", h:`Deixe ele escrever, rode e ajuste.`, b:`Não funcionou? Cola o erro e pede pra corrigir.`},
  {kind:"practice", k:"mão na massa", p:`O script que me poupou tempo: juntar 12 planilhas num relatório. Levou <b class="a">15</b> min.`},
  {kind:"cta", k:"seu próximo passo", h:`Salva esse passo a passo.`, b:`Marca alguém que vai começar com você.`},
]},
// ===== Claude Code =====
{ slug:"c07-claude-x-claudecode", pilar:"Claude Code", title:"Claude comum x Claude Code: a diferenca que ninguem explica", slides:[
  {kind:"cover", k:"Claude Code", h:`Você usa o Claude no navegador. O Claude Code é <b class="a">outra</b> coisa.`, b:`E melhor pro trabalho.`},
  {kind:"mid", k:"Claude comum", h:`Conversa. Não age.`, b:`Ótimo pra tirar dúvida, escrever, explicar.`},
  {kind:"mid", k:"Claude Code", h:`Lê seus arquivos, edita e <b class="a">roda</b> comandos.`, b:`Trabalha dentro do projeto, não só no chat.`},
  {kind:"mid", k:"exemplo", h:`Revisar um projeto inteiro.`, b:`Ele mapeia, aponta riscos e sugere melhorias — direto nos arquivos.`},
  {kind:"practice", k:"mão na massa", p:`O que eu peço: “entenda este projeto e me explique o fluxo principal”.`},
  {kind:"cta", k:"sua vez", h:`Salva.`, b:`Envia pro dev/automatizador que só usa o chat.`},
]},
{ slug:"c08-entender-projeto", pilar:"Claude Code", title:"Use Claude Code pra ENTENDER um projeto que nao e seu", slides:[
  {kind:"cover", k:"Claude Code", h:`Caiu num projeto que você não fez? Ele te explica em <b class="a">minutos</b>.`, b:`Adeus, desespero do código herdado.`},
  {kind:"mid", k:"o problema", h:`Código herdado assusta.`, b:`Você não sabe por onde começar nem o que pode quebrar.`},
  {kind:"mid", k:"peça 1 e 2", h:`Peça um mapa da pasta e o fluxo principal.`, b:`“O que é cada parte e como elas conversam?”`},
  {kind:"mid", k:"peça 3", h:`Peça os <b class="a">riscos</b>.`, b:`“Onde isso pode quebrar se eu mexer?” — antes de tocar em nada.`},
  {kind:"practice", k:"mão na massa", p:`Prompt de onboarding: “me dê um tour deste repositório como se eu fosse novo aqui”.`},
  {kind:"cta", k:"sua vez", h:`Salva pro próximo projeto herdado.`, b:`Comenta se você já passou por isso.`},
]},
{ slug:"c09-subagents", pilar:"Claude Code", title:"Subagents: o recurso de 2026 que multiplica o Claude Code", slides:[
  {kind:"cover", k:"Claude Code · avançado", h:`Um Claude Code é bom. <b class="a">Vários</b> juntos é outro nível.`, b:`Conheça os subagents.`},
  {kind:"mid", k:"o que é", h:`Um Claude isolado, com a própria memória.`, b:`O “chefe” distribui tarefas pra vários ao mesmo tempo.`},
  {kind:"mid", k:"a regra", h:`Skill ensina · Hook obriga · Subagent <b class="a">isola</b>.`, b:`Cada um cuida de uma parte sem atrapalhar o outro.`},
  {kind:"mid", k:"quando usa", h:`Tarefas que se dividem.`, b:`Um explora, outro revisa, outro testa — em paralelo.`},
  {kind:"practice", k:"mão na massa", p:`Meu setup: 1 subagent mapeia, 1 escreve, 1 confere. Tudo numa sessão.`},
  {kind:"cta", k:"sua vez", h:`Salva. Tema avançado.`, b:`Comenta se quer um vídeo só disso.`},
]},
{ slug:"c10-contexto-claudemd", pilar:"Claude Code", title:"Claude Code + contexto: arquivos, arquitetura e CLAUDE.md", slides:[
  {kind:"cover", k:"Claude Code", h:`A IA não “esquece”. Você não deu <b class="a">contexto</b>.`, b:`Resolve com 1 arquivo.`},
  {kind:"mid", k:"a virada", h:`Contexto vence prompt esperto.`, b:`Quanto mais ela enxerga do projeto, melhor a resposta.`},
  {kind:"mid", k:"o CLAUDE.md", h:`Um arquivo que “apresenta” o projeto.`, b:`Regras, padrões, o que evitar, como rodar.`},
  {kind:"mid", k:"o que pôr", h:`Stack · convenções · o “não faça isso”.`, b:`A IA lê uma vez e para de errar o óbvio.`},
  {kind:"practice", k:"mão na massa", p:`Meu CLAUDE.md mínimo: 10 linhas com stack, padrão de código e comando de teste.`},
  {kind:"cta", k:"seu próximo passo", h:`Salva esse modelo de contexto.`, b:`Cria o seu hoje.`},
]},
{ slug:"c11-3-automacoes-noite", pilar:"Claude Code", title:"3 automacoes que montei com Claude Code numa noite", slides:[
  {kind:"cover", k:"Claude Code", h:`Numa <b class="a">noite</b>, montei 3 automações com Claude Code.`, b:`Olha o que dá pra fazer.`},
  {kind:"mid", k:"automação 1", h:`Organizar e renomear arquivos.`, b:`Pasta bagunçada virou estrutura por data e tipo.`},
  {kind:"mid", k:"automação 2", h:`Relatório automático.`, b:`Lê uma planilha e cospe um resumo formatado.`},
  {kind:"mid", k:"automação 3", h:`Integração simples entre dois apps.`, b:`Pegou dados de um, jogou no outro, sem copiar e colar.`},
  {kind:"practice", k:"mão na massa", p:`A mais útil: o relatório. Prompt: “leia este CSV e gere um resumo por mês”.`},
  {kind:"cta", k:"sua vez", h:`Salva.`, b:`Qual dessas você faria primeiro?`},
]},
{ slug:"c12-skills", pilar:"Claude Code", title:"Skills: ensine o agente a trabalhar do seu jeito", slides:[
  {kind:"cover", k:"Claude Code · avançado", h:`Cansou de repetir o mesmo prompt? Vira uma <b class="a">Skill</b>.`, b:`E o agente já sabe o que fazer.`},
  {kind:"mid", k:"o que é", h:`Uma instrução reutilizável.`, b:`Você empacota um jeito de trabalhar e o agente segue sempre.`},
  {kind:"mid", k:"skill x prompt", h:`Prompt some. Skill <b class="a">fica</b>.`, b:`Em vez de reescrever, você invoca.`},
  {kind:"mid", k:"anatomia", h:`Nome · descrição · passos.`, b:`Quando usar e o que fazer, em um arquivo.`},
  {kind:"practice", k:"mão na massa", p:`Skill do meu canal: “gerar carrossel ZocLabs” — copy + arte no meu padrão.`},
  {kind:"cta", k:"sua vez", h:`Salva. Tema avançado.`, b:`Quer um tutorial? Comenta.`},
]},
// ===== Power Automate =====
{ slug:"c13-fluxo-iniciante", pilar:"Power Automate", title:"O fluxo que todo iniciante em Power Automate deveria criar", slides:[
  {kind:"cover", k:"Power Automate", h:`Se você só vai criar <b class="a">UM</b> fluxo, crie esse.`, b:`O primeiro certo te devolve horas — e mostra como o resto funciona.`},
  {kind:"mid", k:"o problema", h:`Toda semana, a <b class="a">mesma</b> tarefa manual.`, b:`Você baixa, arrasta, renomeia, avisa. De novo. E de novo.`},
  {kind:"mid", k:"o segredo", h:`Todo fluxo são 3 peças: Gatilho → Condição → Ação.`, b:`Quando rodar · só se… · o que fazer. Decorou isso, decorou Power Automate.`},
  {kind:"mid", k:"como monta", h:`Gatilho “chegou e-mail” → Ação “salvar” → aviso no Teams.`, b:`Sem código, arrastando blocos.`},
  {kind:"practice", k:"mão na massa", p:`Anexo de e-mail → pasta no SharePoint + aviso no Teams. Monta em <b class="a">15</b> min.`},
  {kind:"cta", k:"seu próximo passo", h:`Salva pra montar hoje.`, b:`Envia pro colega preso no Excel.`},
]},
{ slug:"c14-anexos-sharepoint", pilar:"Power Automate", title:"Salve anexos de e-mail no SharePoint sem codigo", slides:[
  {kind:"cover", k:"Power Automate", h:`Seu e-mail vira pasta organizada — <b class="a">sozinho</b>.`, b:`Sem código. Em 4 passos.`},
  {kind:"mid", k:"o problema", h:`Baixar e arrastar anexo à mão? Chega.`, b:`Todo dia o mesmo ritual. Dá pra automatizar.`},
  {kind:"mid", k:"passo 1 e 2", h:`Gatilho: “quando chegar e-mail”. Condição: “tem anexo?”`, b:`Sem anexo, ignora.`},
  {kind:"mid", k:"passo 3", h:`Ação: salvar no SharePoint.`, b:`Use o <b class="a">Apply to each</b> pra não perder e-mail com vários anexos.`},
  {kind:"practice", k:"mão na massa", p:`Passo 4: avisa no Teams “arquivo salvo”. Pronto: <b class="a">zero</b> arrastar manual.`},
  {kind:"cta", k:"seu próximo passo", h:`Salva pra montar.`, b:`Passo a passo em português no link da bio.`},
]},
{ slug:"c15-alerta-teams", pilar:"Power Automate", title:"Alerta no Teams automatico em 4 passos", slides:[
  {kind:"cover", k:"Power Automate", h:`Pare de avisar a equipe na mão. O fluxo posta no Teams <b class="a">sozinho</b>.`, b:`Em 4 passos.`},
  {kind:"mid", k:"quando usa", h:`Prazo, status, erro, novo pedido.`, b:`Tudo que hoje depende de você lembrar de avisar.`},
  {kind:"mid", k:"passo 1 e 2", h:`Gatilho (data/evento) → Ação “Postar no Teams”.`, b:`Escolhe o time e o canal.`},
  {kind:"mid", k:"passo 3 e 4", h:`Monte a mensagem e <b class="a">teste</b>.`, b:`Campos dinâmicos (nome, prazo) e botão Testar antes de confiar.`},
  {kind:"practice", k:"mão na massa", p:`Alerta de tarefa atrasada caindo no canal toda manhã. Ninguém esquece mais.`},
  {kind:"cta", k:"seu próximo passo", h:`Salva esse atalho.`, b:`Envia pro time que vive esquecendo prazo.`},
]},
{ slug:"c16-aprovacao-simples", pilar:"Power Automate", title:"Aprovacao simples no Power Automate (sem planilha)", slides:[
  {kind:"cover", k:"Power Automate", h:`Aprovação por e-mail e planilha? Existe jeito automático e <b class="a">rastreável</b>.`, b:`Sem caça ao “quem aprovou?”.`},
  {kind:"mid", k:"o caos", h:`Aprovação manual se perde.`, b:`E-mail enterrado, planilha desatualizada, ninguém sabe o status.`},
  {kind:"mid", k:"a ação", h:`Use a ação “Aprovações”.`, b:`O fluxo manda o pedido e espera o sim/não.`},
  {kind:"mid", k:"o depois", h:`O que acontece após o <b class="a">sim</b>.`, b:`Registra, notifica e segue — tudo automático.`},
  {kind:"practice", k:"mão na massa", p:`Fluxo de aprovação de pedido de compra: solicitou → gestor aprova → registra sozinho.`},
  {kind:"cta", k:"sua vez", h:`Salva.`, b:`Envia pro gestor que vive aprovando no e-mail.`},
]},
{ slug:"c17-antes-depois", pilar:"Power Automate", title:"Tarefa manual vira fluxo: antes e depois", slides:[
  {kind:"cover", k:"Power Automate", h:`ANTES: 40 min na mão. DEPOIS: <b class="a">0</b>.`, b:`Mesmo resultado, sem você.`},
  {kind:"mid", k:"a tarefa", h:`Toda sexta: baixar, organizar, mandar relatório.`, b:`Repetitivo, previsível, cansativo.`},
  {kind:"mid", k:"o desperdício", h:`Onde estava o tempo?`, b:`No copia‑e‑cola e no “deixa eu lembrar de avisar”.`},
  {kind:"mid", k:"o fluxo", h:`Gatilho agendado → coleta → envia.`, b:`O mesmo processo, agora automático.`},
  {kind:"practice", k:"mão na massa", p:`Resultado: <b class="a">40</b> min/semana viraram zero. O fluxo roda enquanto você dorme.`},
  {kind:"cta", k:"sua vez", h:`Comenta uma tarefa sua que daria pra automatizar.`, b:`Salva o modelo antes/depois.`},
]},
{ slug:"c18-powerautomate-agentes", pilar:"Power Automate", title:"Power Automate agora tem agentes de IA: o que muda", slides:[
  {kind:"cover", k:"Power Automate", h:`Power Automate + agentes de IA: seu fluxo agora <b class="a">pensa</b>.`, b:`O que muda em 2026.`},
  {kind:"mid", k:"AI actions", h:`Ações de IA dentro do fluxo.`, b:`Entender um pedido, classificar, gerar texto — no meio da automação.`},
  {kind:"mid", k:"roteamento", h:`O fluxo decide o caminho.`, b:`“Isso é reclamação ou elogio?” e segue diferente pra cada um.`},
  {kind:"mid", k:"MCP Server", h:`Conecte <b class="a">agentes</b> ao fluxo.`, b:`A automação vira ferramenta que um agente de IA usa.`},
  {kind:"practice", k:"mão na massa", p:`Ideia: e-mail chega → IA resume → fluxo cria tarefa com o resumo. Tudo sozinho.`},
  {kind:"cta", k:"sua vez", h:`Salva.`, b:`Comenta se quer ver montando.`},
]},
{ slug:"c19-self-healing", pilar:"Power Automate", title:"Self-healing: fluxos que se consertam sozinhos em 2026", slides:[
  {kind:"cover", k:"Power Automate", h:`Seu fluxo quebrou porque mudaram um botão? Ele se <b class="a">conserta</b>.`, b:`Self-healing chegou.`},
  {kind:"mid", k:"por que quebra", h:`Automação é frágil a mudança.`, b:`Mudou a tela, mudou o nome do campo — e parou.`},
  {kind:"mid", k:"o que é", h:`O fluxo se adapta sozinho.`, b:`Detecta a mudança e ajusta o passo sem você.`},
  {kind:"mid", k:"onde já tem", h:`Começa nos <b class="a">desktop</b> flows.`, b:`Automações de tela ganham resiliência.`},
  {kind:"practice", k:"mão na massa", p:`Como me preparo: documento o fluxo e separo o que é estável do que muda muito.`},
  {kind:"cta", k:"sua vez", h:`Salva esse conceito novo.`, b:`Comenta se já te aconteceu.`},
]},
// ===== Power Apps =====
{ slug:"c20-app-anexos-sharepoint", pilar:"Power Apps", title:"App em 30 min: enviar anexos do Power Apps pro SharePoint", slides:[
  {kind:"cover", k:"Power Apps", h:`Um app que envia anexos pra uma pasta do SharePoint. Em <b class="a">30</b> min.`, b:`Seu 1º app útil de verdade.`},
  {kind:"mid", k:"o caso", h:`Gente mandando arquivo por e-mail e se perdendo.`, b:`Um app centraliza tudo no lugar certo.`},
  {kind:"mid", k:"a tela", h:`Formulário + campo de anexo.`, b:`Quem usa só preenche e anexa.`},
  {kind:"mid", k:"o botão", h:`Botão de envio → <b class="a">SharePoint</b>.`, b:`O arquivo cai na pasta automaticamente.`},
  {kind:"practice", k:"mão na massa", p:`App pronto: preenche, anexa, envia. Os arquivos aparecem organizados na pasta.`},
  {kind:"cta", k:"seu próximo passo", h:`Salva.`, b:`Esse é o seu primeiro Power App.`},
]},
{ slug:"c21-tela-solicitacao", pilar:"Power Apps", title:"Tela de solicitacao interna: form + galeria + botao", slides:[
  {kind:"cover", k:"Power Apps", h:`RH, TI, compras… toda área precisa de uma tela de <b class="a">solicitação</b>.`, b:`Faz a sua.`},
  {kind:"mid", k:"o problema", h:`Solicitação no Word/e-mail vira bagunça.`, b:`Sem padrão, sem histórico, sem status.`},
  {kind:"mid", k:"o formulário", h:`Campos do pedido, organizados.`, b:`Quem solicita preenche em segundos.`},
  {kind:"mid", k:"galeria + botão", h:`Veja os pedidos e <b class="a">envie</b>.`, b:`Galeria lista tudo; botão registra a nova solicitação.`},
  {kind:"practice", k:"mão na massa", p:`App de solicitação interna: formulário, lista dos pedidos e botão de envio. Pronto.`},
  {kind:"cta", k:"sua vez", h:`Salva.`, b:`Envia pra quem ainda usa formulário no Word.`},
]},
{ slug:"c22-checklist", pilar:"Power Apps", title:"App de checklist no Power Apps do zero", slides:[
  {kind:"cover", k:"Power Apps", h:`Checklist no papel se perde. Esse app <b class="a">salva</b> sozinho.`, b:`Do zero, projeto pequeno.`},
  {kind:"mid", k:"por que", h:`Processo sem checklist erra.`, b:`E checklist no papel ninguém acha depois.`},
  {kind:"mid", k:"a lista", h:`Itens do processo, na tela.`, b:`Cada etapa vira um item marcável.`},
  {kind:"mid", k:"marcar e salvar", h:`Marcou → <b class="a">salvou</b>.`, b:`Histórico de quem fez e quando, automático.`},
  {kind:"practice", k:"mão na massa", p:`Checklist de abertura de loja: marca cada item, salva e gera o registro do dia.`},
  {kind:"cta", k:"sua vez", h:`Salva esse projeto.`, b:`Envia pra quem ama um checklist.`},
]},
{ slug:"c23-powerapp-com-ia", pilar:"Power Apps", title:"Construa um Power App CONVERSANDO com IA (MCP authoring)", slides:[
  {kind:"cover", k:"Power Apps", h:`Você descreve a tela. A IA <b class="a">constrói</b> o Power App.`, b:`Isso é real em 2026.`},
  {kind:"mid", k:"o que é", h:`Canvas Apps MCP Authoring.`, b:`Montar app em linguagem natural, sem arrastar tudo na mão.`},
  {kind:"mid", k:"como", h:`Use Claude Code ou Copilot como construtor.`, b:`Você fala; ele gera a tela em YAML validado.`},
  {kind:"mid", k:"o que revisar", h:`A IA constrói; você <b class="a">confere</b>.`, b:`Ajusta nomes, dados e permissões antes de publicar.`},
  {kind:"practice", k:"mão na massa", p:`Pedi falando: “tela com formulário e botão que salva no SharePoint”. Saiu pronta.`},
  {kind:"cta", k:"sua vez", h:`Salva. É o futuro do low-code.`, b:`Comenta se quer ver montando.`},
]},
{ slug:"c24-app-skills", pilar:"Power Apps", title:"App Skills: seu Power App vira ferramenta de agente", slides:[
  {kind:"cover", k:"Power Apps · avançado", h:`Seu Power App pode virar uma <b class="a">ferramenta</b> que um agente usa.`, b:`Conheça as App Skills.`},
  {kind:"mid", k:"o que é", h:`Funções do app expostas como ferramenta.`, b:`Form e grid viram algo que a IA consegue operar.`},
  {kind:"mid", k:"via MCP", h:`O app publica suas “habilidades”.`, b:`Um agente lê, entende e usa — sem abrir a tela.`},
  {kind:"mid", k:"o que muda", h:`O agente <b class="a">trabalha</b> no seu app.`, b:`Consulta, preenche, resume — autônomo e supervisionável.`},
  {kind:"practice", k:"mão na massa", p:`Cenário: agente lê pedidos no seu app e responde status sozinho, no chat da empresa.`},
  {kind:"cta", k:"sua vez", h:`Salva. Tema avançado.`, b:`Quer um tutorial? Comenta.`},
]},
{ slug:"c25-erros-powerapps", pilar:"Power Apps", title:"5 erros de iniciante no Power Apps", slides:[
  {kind:"cover", k:"Power Apps", h:`<b class="a">5</b> erros que todo iniciante comete no Power Apps.`, b:`Eu cometi todos.`},
  {kind:"mid", k:"erro 1 e 2", h:`Controles sem nome. Dados sem fonte organizada.`, b:`Depois vira impossível de manter.`},
  {kind:"mid", k:"erro 3", h:`Uma tela gigante pra tudo.`, b:`Quebra em telas: mais simples de usar e arrumar.`},
  {kind:"mid", k:"erro 4 e 5", h:`Não testar. Esquecer <b class="a">permissão</b>.`, b:`O app “funciona pra você” e quebra pro resto.`},
  {kind:"practice", k:"mão na massa", p:`Como evito hoje: nomeio tudo, separo a fonte de dados e testo com outra conta.`},
  {kind:"cta", k:"sua vez", h:`Qual erro você já cometeu?`, b:`Salva a lista e comenta.`},
]},
// ===== IA + Automação (glue) =====
{ slug:"c26-3-automacoes-simples", pilar:"IA + Automação", title:"3 automacoes simples que economizam horas por semana", slides:[
  {kind:"cover", k:"IA + Automação", h:`<b class="a">3</b> automações simples que me devolvem horas toda semana.`, b:`Nenhuma exige código.`},
  {kind:"mid", k:"automação 1", h:`Anexo de e-mail → pasta.`, b:`Nunca mais baixar e arrastar arquivo na mão.`},
  {kind:"mid", k:"automação 2", h:`Alerta de prazo no Teams.`, b:`O time é avisado sozinho, no horário certo.`},
  {kind:"mid", k:"automação 3", h:`Relatório automático.`, b:`Coleta os dados e manda formatado, sem você.`},
  {kind:"practice", k:"mão na massa", p:`A que mais me salva: o alerta de prazo. <b class="a">2</b> horas/semana de volta.`},
  {kind:"cta", k:"sua vez", h:`Salva.`, b:`Envia pro colega afogado em tarefa repetitiva.`},
]},
{ slug:"c27-comecar-hoje", pilar:"IA + Automação", title:"O que eu faria se comecasse em automacao HOJE", slides:[
  {kind:"cover", k:"IA + Automação", h:`Se eu começasse em automação <b class="a">hoje</b>, faria nessa ordem.`, b:`E pularia o que me fez perder tempo.`},
  {kind:"mid", k:"passo 1", h:`1 fluxo real, não curso infinito.`, b:`Aprender fazendo vale por dez vídeos assistidos.`},
  {kind:"mid", k:"passo 2", h:`Power Automate antes de código.`, b:`Resolve 80% das dores sem programar.`},
  {kind:"mid", k:"passo 3 e 4", h:`IA como copiloto. Documentar pra <b class="a">ensinar</b>.`, b:`Quem ensina, aprende em dobro.`},
  {kind:"practice", k:"mão na massa", p:`Meu caminho: 1º fluxo de anexos → alertas → relatórios → IA por cima.`},
  {kind:"cta", k:"seu próximo passo", h:`Salva esse roteiro de começo.`, b:`Marca quem vai começar com você.`},
]},
{ slug:"c28-lowcode-x-codigo", pilar:"IA + Automação", title:"Low-code x codigo: quando usar cada um", slides:[
  {kind:"cover", k:"IA + Automação", h:`Low-code ou código? Usar o errado custa <b class="a">semanas</b>.`, b:`Como eu decido.`},
  {kind:"mid", k:"low-code ganha", h:`Processo interno, rápido, sem muita regra.`, b:`Aprovações, formulários, alertas, apps simples.`},
  {kind:"mid", k:"código ganha", h:`Regra complexa, escala, integração pesada.`, b:`Quando o low-code começa a “lutar” contra você.`},
  {kind:"mid", k:"zona cinzenta", h:`Comece <b class="a">low-code</b>.`, b:`Migra pra código só quando bater o limite — e aí já validou a ideia.`},
  {kind:"practice", k:"mão na massa", p:`Regra de bolso: protótipo em low-code; virou produto sério, repenso em código.`},
  {kind:"cta", k:"sua vez", h:`Comenta seu caso.`, b:`Eu te digo qual eu usaria. Salva.`},
]},
{ slug:"c29-agentes-explicados", pilar:"IA + Automação", title:"Agentes de IA explicados sem enrolacao", slides:[
  {kind:"cover", k:"IA + Automação", h:`Todo mundo fala “agente de IA” e ninguém <b class="a">explica</b>.`, b:`Vou explicar em 1 carrossel.`},
  {kind:"mid", k:"chatbot x agente", h:`Chatbot responde. Agente resolve.`, b:`Um conversa; o outro vai e faz.`},
  {kind:"mid", k:"o que faz", h:`Pensa · age · <b class="a">verifica</b>.`, b:`Planeja a tarefa, executa os passos e confere o resultado.`},
  {kind:"mid", k:"exemplo", h:`No trabalho:`, b:`“Organize estes pedidos e me avise os atrasados” — e ele faz tudo.`},
  {kind:"practice", k:"mão na massa", p:`Um agente que uso: lê uma pasta, resume os arquivos e gera um relatório sozinho.`},
  {kind:"cta", k:"sua vez", h:`Salva.`, b:`Envia pra quem confunde tudo com “ChatGPT”.`},
]},
{ slug:"c30-meu-setup", pilar:"IA + Automação", title:"Meu setup de IA pra trabalhar", slides:[
  {kind:"cover", k:"IA + Automação", h:`Meu setup pra trabalhar com IA cabe em <b class="a">3</b> ferramentas.`, b:`E por que cada uma.`},
  {kind:"mid", k:"Codex", h:`Pro terminal e tarefas repetitivas.`, b:`Organiza arquivos, roda scripts, opera o PC.`},
  {kind:"mid", k:"Claude Code", h:`Pra entender e mexer em projeto.`, b:`Contexto, arquitetura, revisão — direto nos arquivos.`},
  {kind:"mid", k:"Power Platform", h:`Pro <b class="a">corporativo</b>.`, b:`Power Automate e Power Apps onde a empresa já vive (Office/Teams).`},
  {kind:"practice", k:"mão na massa", p:`Um dia típico: Codex limpa dados, Claude Code ajusta o projeto, Power Automate avisa o time.`},
  {kind:"cta", k:"sua vez", h:`Salva esse setup.`, b:`Qual você já usa? Comenta.`},
]},
];
